# Generated by Django 3.1.4 on 2020-12-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.TextField(max_length=255)),
                ('bairro', models.TextField(max_length=100)),
                ('numero', models.IntegerField()),
                ('complemento', models.TextField(blank=True, max_length=100, null=True)),
                ('cidade', models.TextField(max_length=60)),
                ('estado', models.TextField(max_length=60)),
                ('latitude', models.IntegerField(blank=True, null=True)),
                ('longitude', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
